stages:
  - test        # Run tests first
  - build       # Build Docker image
  - deploy      # Deploy to kubernetes

# Test stage (Python app)
test-app:
  stage: test
  image: python:3.11-slim
  script:                  # This runs on every single push to the repository
    - cd app         # ← move into app folder first
    - pip install fastapi uvicorn pytest httpx
    - pytest tests/test_main.py -v

# Build and push stage (Docker image)
build-image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind     # Docker-in-Docker service for building images
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA ./app
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - main                 # Only build and push on the main branch

# Deploy stage to Kubernetes
deploy-staging:
  stage: deploy
  image: alpine/helm:3.14.0
  before_script:
    # Install AWS CLI inside the helm image to configure access
    - apk add --no-cache aws-cli
    # Use the variables you saved in GitLab settings to connect to EKS
    - aws eks update-kubeconfig --name hello-bank-eks --region $AWS_DEFAULT_REGION
    # This command creates the namespace and secret if they don't exist 
    - kubectl create namespace hello-bank --dry-run=client -o yaml | kubectl apply -f -
    - kubectl create secret docker-registry gitlab-registry-key 
        --docker-server=$CI_REGISTRY 
        --docker-username=$CI_REGISTRY_USER 
        --docker-password=$CI_REGISTRY_PASSWORD 
        --namespace hello-bank 
        --dry-run=client -o yaml | kubectl apply -f -
  script:
    - helm upgrade --install hello-bank ./kubernetes/helm/hello-bank-app
      --set image.tag=$CI_COMMIT_SHA
      --namespace hello-bank
      --create-namespace
    - aws eks update-kubeconfig --name hello-bank-eks --region $AWS_DEFAULT_REGION
    # Create the RDS secret for the app to use
    - kubectl create secret generic rds-credentials --from-literal=password=$TF_VAR_db_password -n hello-bank --dry-run=client -o yaml | kubectl apply -f -
    # Deploy the app
    - helm upgrade --install hello-bank ./kubernetes/helm/hello-bank-app ...
  only:
    - main                 # Only deploy on the main branch
  when: manual              # Manual trigger for deployment ( You click a button to deploy — no accidental deploys)

deploy-monitoring:
  stage: deploy
  image: alpine/helm:3.14.0
  script:
    - aws eks update-kubeconfig --name hello-bank-eks --region $AWS_DEFAULT_REGION
    # Create the secret if it doesn't exist
    - kubectl create secret generic datadog-secret --from-literal=api-key=$DATADOG_API_KEY -n monitoring --dry-run=client -o yaml | kubectl apply -f -
    # Install Datadog
    - helm repo add datadog https://helm.datadoghq.com
    - helm upgrade --install datadog-agent datadog/datadog -f monitoring/datadog-values.yaml -n monitoring

# GitLab will "mask" the password in the logs (it will show as [MASKED]) to protect your security.
debug-registry:
  stage: test
  script:
    - echo "The registry user is $CI_REGISTRY_USER"

    - echo "The registry URL is $CI_REGISTRY"