apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-user
spec:
  validationFailureAction: enforce
  rules:
    - name: disallow-root-user
      match:
        resources:
          kinds: [Pod]
      validate:
        message: "Running as root user is not allowed."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
