apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-bank-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-bank-svc
                port:
                  number: 80